// ============================================================
// Generated by Morph x402 Onboarding Wizard
// Network     : Hoodi Testnet (chainID 2910)
// Token       : HoodiTestToken (0xEcF966Cc754BC411E1F1106fbb4e343b835E85E4)
// Generated at: 2026-05-15 11:05 UTC+8
// Sanitized for repository use: runtime credentials are loaded from environment variables.
// ============================================================

package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	x402 "github.com/x402-foundation/x402/go"
	x402http "github.com/x402-foundation/x402/go/http"
	ginmw "github.com/x402-foundation/x402/go/http/gin"
	evmServer "github.com/x402-foundation/x402/go/mechanisms/evm/exact/server"
	"github.com/gin-gonic/gin"
)

var (
	serviceName    = "my-x402-service"
	facilitatorURL = envOr("MORPH_HOODI_X402_FACILITATOR_URL", "https://morph-rails-hoodi.morph.network/x402/v2")
	accessKey      = mustEnv("MORPH_X402_ACCESS_KEY")
	secretKey      = mustEnv("MORPH_X402_SECRET_KEY")

	chainID      = mustEnvInt64("MORPH_HOODI_CHAIN_ID", 2910)
	tokenAddress = envOr("MORPH_HOODI_TOKEN_ADDRESS", "0xEcF966Cc754BC411E1F1106fbb4e343b835E85E4")
	tokenName    = envOr("MORPH_HOODI_TOKEN_NAME", "HoodiTestToken")
	// tokenVersion comes from the EIP-712 domain — it MUST match the token contract's version().
	// How to find it: call tokenContract.version() on-chain, or read the contract source.
	tokenVersion   = envOr("MORPH_HOODI_TOKEN_VERSION", "1.0")
	tokenDecimals  = mustEnvInt("MORPH_HOODI_TOKEN_DECIMALS", 18)
	payToAddress   = mustEnv("MORPH_X402_PAYTO_ADDRESS")
	price          = envOr("MORPH_X402_PRICE", "0.001")
	port           = envOr("MORPH_X402_DEMO_PORT", ":8000")
	provider       = envOr("MANDATE402_MARKET_PROVIDER", "demo")
	cmcBaseURL     = envOr("CMC_BASE_URL", "https://pro-api.coinmarketcap.com")
	cmcAPIKey      = envOr("CMC_API_KEY", "")
	coinAPIBaseURL = envOr("COINAPI_BASE_URL", "https://rest.coinapi.io")
	coinAPIKey     = envOr("COINAPI_KEY", "")
	requestTimeout = 60 * time.Second
)

type paymentRecord struct {
	ChargeReference string `json:"chargeReference"`
	Status          string `json:"status"`
	ReceiptEvidence string `json:"receiptEvidence"`
	Resource        string `json:"resource"`
	CreatedAt       string `json:"createdAt"`
}

type marketPayload struct {
	Provider       string         `json:"provider"`
	Asset          string         `json:"asset"`
	QuoteCurrency  string         `json:"quoteCurrency"`
	Price          string         `json:"price"`
	PercentChange1h string        `json:"percentChange1h,omitempty"`
	PercentChange24h string       `json:"percentChange24h,omitempty"`
	Timestamp      string         `json:"timestamp"`
	Raw            map[string]any `json:"raw,omitempty"`
}

type paymentStore struct {
	mu        sync.RWMutex
	byPID     map[string]paymentRecord
	byCharge  map[string]paymentRecord
}

type statusRequest struct {
	ChargeReference string `json:"chargeReference"`
}

func newPaymentStore() *paymentStore {
	return &paymentStore{
		byPID:    make(map[string]paymentRecord),
		byCharge: make(map[string]paymentRecord),
	}
}

type providerClient struct {
	httpClient *http.Client
}

func (s *paymentStore) put(paymentIdentifier string, record paymentRecord) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.byPID[paymentIdentifier] = record
	s.byCharge[record.ChargeReference] = record
}

func (s *paymentStore) get(paymentIdentifier, chargeReference string) (paymentRecord, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if paymentIdentifier != "" {
		record, ok := s.byPID[paymentIdentifier]
		if ok {
			return record, true
		}
	}

	if chargeReference != "" {
		record, ok := s.byCharge[chargeReference]
		if ok {
			return record, true
		}
	}

	return paymentRecord{}, false
}

func envOr(key, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return fallback
}

func (p *providerClient) fetchJSON(req *http.Request, target any) error {
	resp, err := p.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("provider request failed: %s %s", resp.Status, string(body))
	}

	return json.NewDecoder(resp.Body).Decode(target)
}

func (p *providerClient) fetchMarketData() (marketPayload, error) {
	switch strings.ToLower(provider) {
	case "coinmarketcap", "cmc":
		return p.fetchCoinMarketCapMarketData()
	case "coinapi":
		return p.fetchCoinAPIMarketData()
	default:
		return marketPayload{
			Provider:        "demo",
			Asset:           "ETH",
			QuoteCurrency:   "USD",
			Price:           "2500.00",
			PercentChange1h: "0.32",
			PercentChange24h:"4.91",
			Timestamp:       time.Now().UTC().Format(time.RFC3339),
			Raw: map[string]any{
				"note": "demo fallback payload",
			},
		}, nil
	}
}

func (p *providerClient) fetchCoinMarketCapMarketData() (marketPayload, error) {
	if cmcAPIKey == "" {
		return marketPayload{}, fmt.Errorf("CMC_API_KEY is required for CoinMarketCap provider")
	}

	req, err := http.NewRequest(
		http.MethodGet,
		fmt.Sprintf("%s/v2/cryptocurrency/quotes/latest?symbol=ETH&convert=USD", strings.TrimRight(cmcBaseURL, "/")),
		nil,
	)
	if err != nil {
		return marketPayload{}, err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("X-CMC_PRO_API_KEY", cmcAPIKey)

	var response struct {
		Data map[string][]struct {
			Name  string `json:"name"`
			Symbol string `json:"symbol"`
			Quote map[string]struct {
				Price            float64 `json:"price"`
				PercentChange1h  float64 `json:"percent_change_1h"`
				PercentChange24h float64 `json:"percent_change_24h"`
				LastUpdated      string  `json:"last_updated"`
			} `json:"quote"`
		} `json:"data"`
	}
	if err := p.fetchJSON(req, &response); err != nil {
		return marketPayload{}, err
	}

	entries := response.Data["ETH"]
	if len(entries) == 0 {
		return marketPayload{}, fmt.Errorf("CoinMarketCap returned no ETH data")
	}
	quote := entries[0].Quote["USD"]

	return marketPayload{
		Provider:         "coinmarketcap",
		Asset:            entries[0].Symbol,
		QuoteCurrency:    "USD",
		Price:            fmt.Sprintf("%.2f", quote.Price),
		PercentChange1h:  fmt.Sprintf("%.2f", quote.PercentChange1h),
		PercentChange24h: fmt.Sprintf("%.2f", quote.PercentChange24h),
		Timestamp:        quote.LastUpdated,
	}, nil
}

func (p *providerClient) fetchCoinAPIMarketData() (marketPayload, error) {
	if coinAPIKey == "" {
		return marketPayload{}, fmt.Errorf("COINAPI_KEY is required for CoinAPI provider")
	}

	req, err := http.NewRequest(
		http.MethodGet,
		fmt.Sprintf("%s/v1/exchangerate/ETH/USD", strings.TrimRight(coinAPIBaseURL, "/")),
		nil,
	)
	if err != nil {
		return marketPayload{}, err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("X-CoinAPI-Key", coinAPIKey)

	var response struct {
		AssetIDBase  string  `json:"asset_id_base"`
		AssetIDQuote string  `json:"asset_id_quote"`
		Rate         float64 `json:"rate"`
		Time         string  `json:"time"`
	}
	if err := p.fetchJSON(req, &response); err != nil {
		return marketPayload{}, err
	}

	return marketPayload{
		Provider:      "coinapi",
		Asset:         response.AssetIDBase,
		QuoteCurrency: response.AssetIDQuote,
		Price:         fmt.Sprintf("%.2f", response.Rate),
		Timestamp:     response.Time,
	}, nil
}

func mustEnv(key string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		panic(fmt.Sprintf("missing required environment variable: %s", key))
	}
	return value
}

func mustEnvInt(key string, fallback int) int {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		panic(fmt.Sprintf("invalid integer for %s: %v", key, err))
	}
	return parsed
}

func mustEnvInt64(key string, fallback int64) int64 {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		panic(fmt.Sprintf("invalid int64 for %s: %v", key, err))
	}
	return parsed
}

// ========== HMAC Transport (Morph authentication — generic template, do not modify) ==========
func morphBuildSignContent(accessKey, timestamp, method, path, rawQuery, rawBody string) []byte {
	signMap := map[string]interface{}{
		"MORPH-ACCESS-KEY":       accessKey,
		"MORPH-ACCESS-TIMESTAMP": timestamp,
		"MORPH-ACCESS-METHOD":    method,
		"MORPH-ACCESS-PATH":      path,
	}
	if rawQuery != "" {
		values, _ := url.ParseQuery(rawQuery)
		for k, vs := range values {
			signMap[k] = vs
		}
	}
	if rawBody != "" {
		var bodyObj interface{}
		if err := json.Unmarshal([]byte(rawBody), &bodyObj); err == nil {
			signMap["MORPH-ACCESS-BODY"] = bodyObj
		}
	}
	content, _ := json.Marshal(signMap)
	return content
}

func morphSign(accessKey, secretKey, timestamp, method, path, rawQuery, rawBody string) string {
	content := morphBuildSignContent(accessKey, timestamp, method, path, rawQuery, rawBody)
	mac := hmac.New(sha256.New, []byte(secretKey))
	mac.Write(content)
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}

type morphSignTransport struct {
	accessKey string
	secretKey string
	base      http.RoundTripper
}

func (t *morphSignTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	timestamp := strconv.FormatInt(time.Now().UnixMilli(), 10)
	rawQuery := req.URL.RawQuery
	var rawBody string
	if req.Body != nil {
		bodyBytes, err := io.ReadAll(req.Body)
		if err != nil {
			return nil, err
		}
		rawBody = string(bodyBytes)
		req.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
	}
	// Canonical signature path is always "/x402/v2/...". When facilitatorURL
	// already contains the "/x402" gateway prefix (e.g. morph-rails-hoodi.morph.network/x402/v2),
	// req.URL.Path already has it — avoid double-prefixing.
	signPath := req.URL.Path
	if !strings.HasPrefix(signPath, "/x402") {
		signPath = "/x402" + signPath
	}
	sign := morphSign(t.accessKey, t.secretKey, timestamp, req.Method, signPath, rawQuery, rawBody)

	req.Header.Set("MORPH-ACCESS-KEY", t.accessKey)
	req.Header.Set("MORPH-ACCESS-TIMESTAMP", timestamp)
	req.Header.Set("MORPH-ACCESS-SIGN", sign)
	return t.base.RoundTrip(req)
}

// ========== Main ==========
func main() {
	ctx := context.Background()
	_ = ctx
	store := newPaymentStore()

	httpClient := &http.Client{
		Transport: &morphSignTransport{accessKey: accessKey, secretKey: secretKey, base: http.DefaultTransport},
		Timeout:   requestTimeout,
	}
	dataClient := &providerClient{httpClient: &http.Client{Timeout: requestTimeout}}

	facilitator := x402http.NewHTTPFacilitatorClient(&x402http.FacilitatorConfig{
		URL:        facilitatorURL,
		HTTPClient: httpClient,
	})

	evmServerScheme := evmServer.NewExactEvmScheme()
	evmServerScheme.RegisterMoneyParser(func(amount float64, _ x402.Network) (*x402.AssetAmount, error) {
		amountInSmallestUnits := math.Round(amount * math.Pow10(tokenDecimals))
		return &x402.AssetAmount{
			Amount: fmt.Sprintf("%.0f", amountInSmallestUnits),
			Asset:  tokenAddress,
			Extra: map[string]interface{}{
				"name":    tokenName,
				"version": tokenVersion,
			},
		}, nil
	})

	network := x402.Network(fmt.Sprintf("eip155:%d", chainID))

	routes := x402http.RoutesConfig{
		"POST /x402_demo/api/market-data": {
			Accepts: x402http.PaymentOptions{
				{
					Scheme:            "exact",
					PayTo:             payToAddress,
					Price:             price,
					Network:           network,
					MaxTimeoutSeconds: 15,
				},
			},
			Description: "Mandate402 market data vendor",
			MimeType:    "application/json",
		},
		"POST /x402_demo/api/research": {
			Accepts: x402http.PaymentOptions{
				{
					Scheme:            "exact",
					PayTo:             payToAddress,
					Price:             price,
					Network:           network,
					MaxTimeoutSeconds: 15,
				},
			},
			Description: "Mandate402 research vendor",
			MimeType:    "application/json",
		},
	}

	router := gin.Default()

	router.Use(ginmw.X402Payment(ginmw.Config{
		Routes:      routes,
		Facilitator: facilitator,
		Schemes: []ginmw.SchemeConfig{
			{Network: network, Server: evmServerScheme},
		},
		SyncFacilitatorOnStart: true,
		Timeout:                requestTimeout,
	}))

	router.POST("/x402_demo/api/market-data", func(c *gin.Context) {
		paymentIdentifier := c.GetHeader("X-Payment-Identifier")
		chargeReference := fmt.Sprintf("market_%d", time.Now().UnixMilli())
		payload, err := dataClient.fetchMarketData()
		if err != nil {
			c.JSON(http.StatusBadGateway, gin.H{
				"message": "Provider fetch failed.",
				"error":   err.Error(),
			})
			return
		}
		record := paymentRecord{
			ChargeReference: chargeReference,
			Status:          "executed_charge_succeeded",
			ReceiptEvidence: "received_valid",
			Resource:        "market-data",
			CreatedAt:       time.Now().UTC().Format(time.RFC3339),
		}
		store.put(paymentIdentifier, record)

		c.JSON(200, gin.H{
			"message":         "Payment successful, market data access granted.",
			"chargeReference": chargeReference,
			"receiptEvidence": "received_valid",
			"data":            payload,
			"source":          serviceName,
		})
	})

	router.POST("/x402_demo/api/research", func(c *gin.Context) {
		paymentIdentifier := c.GetHeader("X-Payment-Identifier")
		chargeReference := fmt.Sprintf("research_%d", time.Now().UnixMilli())
		payload, err := dataClient.fetchMarketData()
		if err != nil {
			c.JSON(http.StatusBadGateway, gin.H{
				"message": "Provider fetch failed.",
				"error":   err.Error(),
			})
			return
		}
		record := paymentRecord{
			ChargeReference: chargeReference,
			Status:          "executed_charge_succeeded",
			ReceiptEvidence: "received_valid",
			Resource:        "research",
			CreatedAt:       time.Now().UTC().Format(time.RFC3339),
		}
		store.put(paymentIdentifier, record)

		// Intentionally exceed the Next app's correlation timeout so the app
		// can enter execution_unknown and later reconcile via /status.
		time.Sleep(9 * time.Second)

		c.JSON(200, gin.H{
			"message":         "Payment successful, research access granted.",
			"chargeReference": chargeReference,
			"receiptEvidence": "received_valid",
			"data": gin.H{
				"summary":        "Morph x402 facilitator is payment infrastructure; Mandate402 governs the treasury boundary.",
				"marketSnapshot": payload,
				"source":         serviceName,
			},
		})
	})

	router.POST("/x402_demo/api/market-data/status", func(c *gin.Context) {
		serveStatus(c, store)
	})
	router.POST("/x402_demo/api/research/status", func(c *gin.Context) {
		serveStatus(c, store)
	})

	if err := router.Run(port); err != nil {
		panic(err)
	}
}

func serveStatus(c *gin.Context, store *paymentStore) {
	paymentIdentifier := c.GetHeader("X-Payment-Identifier")
	var body statusRequest
	_ = c.ShouldBindJSON(&body)

	record, ok := store.get(paymentIdentifier, body.ChargeReference)
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{
			"status":          "executed_charge_failed",
			"chargeReference": nil,
			"receiptEvidence": "missing_timeout",
		})
		return
	}

	c.JSON(http.StatusOK, record)
}
